name: Create Release

on: [push, pull_request]
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Release Information
      run: |
          export VERSION_NAME='1.0.0'
          run: echo "VERSION_NAME=1.0.0" >> $GITHUB_ENV
    - name: Create Release
      uses: actions/create-release@v1
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "1.0.0"
        release_name: "v1.0.0"
        artifacts: "*.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
