name: Run Playbook Conditionally

on: [push, workflow_dispatch]
  #workflow_dispatch:

env:
  users_file: 'users'

jobs:
  Run_Playbook_Conditionally:
    name: Run_Playbook_Conditionally
    if: github.triggering_actor == github.repository_owner
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4
    - name: Check for Repo contents
      shell: bash
      run: |
        pwd && ls -ltra
    - name: Users file Content Check
      id: users
      shell: bash
      run: |
        content=$(<users)
        echo "Output: $content"
        if grep -q venkata-subbareddyK "$users_file"; then
          exit 0
        fi
    - name: Check for Repo Context Vars and its Values
      #if: contains ($content, github.triggering_actor)
      if: ${{ steps.users.conclusion == 'success' }}
      shell: bash
      run: |
        pwd && ls -ltra
        echo "User ID:${{ github.actor }}"
        echo "User ID who triggered this workflow:${{ github.triggering_actor }}"
        echo "Repo owner user ID:${{ github.repository_owner }}"
        echo "Repo owner email ID:${{ github.repository_owner.email }}"
        echo "Repo admin user ID:${{ github.repository_admin }}"
        echo "Repo admin:${{ github.admin }}"
        echo "The Name of the pusher: ${{ github.event.pusher.name }}"
        echo "The Email of the pusher: ${{ github.event.pusher.email }}"
