name: Run Playbook Conditionally

on:
  workflow_dispatch:

jobs:
  Run_Playbook_Conditionally:
    name: Run_Playbook_Conditionally
    if: github.triggering_actor == github.repository_owner
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4
    - name: Check for Repo contents
      shell: bash
      run: |
        pwd && ls -ltra
    - name: Check for Repo Context Vars and its Values
      shell: bash
      run: |
        pwd && ls -ltra
        echo ${{ github.actor }}
        echo ${{ github.triggering_actor }}
        echo ${{ github.repository_owner }}
